name: engine-linux
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libasound2-dev libx11-dev libxpm-dev mesa-common-dev libpng-dev libjpeg-dev libwebp-dev libbz2-dev libogg-dev libvorbis-dev libfreetype-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          cd build/engine-linux
          make -f Makefile.linux
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: engine-linux
          path: build/engine-linux/suika
